name: Development Build

on:  
  push:    
    branches:      
      - main  
  workflow_dispatch:

jobs:
  build-pwa:
    uses: ./.github/workflows/build-pwa.yml
    with:
      mode: "dev"

  deploy:
    needs: build-pwa
    runs-on: ubuntu-slim
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: pwa-dist-release
          path: ./apps

      - name: Vercel deploy
        uses: amondnet/vercel-action@v25
        with:
          working-directory: ./apps
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
