name: Project Release Build

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-project:
    uses: ./.github/workflows/build-project.yml
    with:
      mode: "release"

  deploy:
    needs: build-project
    runs-on: ubuntu-slim

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: project-dist-release

      - name: Cloudflare deploy
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: "dist"
