name: Project Dev Build

on:  
  push:    
    branches:
      - main
    paths:
      - 'apps/**'  
  workflow_dispatch:

jobs:
  build-project:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Build project
        uses: ./.github/actions/build-project
        with:
          mode: "dev"

  deploy:
    needs: build-project
    runs-on: ubuntu-slim
    
    steps:
      - name: Cloudflare deploy
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: "dist"
          command: pages deploy ./ --project-name=${{ vars.CLOUDFLARE_PROJECT_NAME }} --branch=${{ vars.CLOUDFLARE_PREVIEW_BRANCH }}
