name: Project Dev Build

on:  
  push:    
    branches:
      - main
    paths:
      - 'apps/**'  
  workflow_dispatch:

jobs:
  build-project:
    uses: ./.github/workflows/build-project.yml
    with:
      mode: "dev"

  deploy:
    needs: build-project
    runs-on: ubuntu-slim
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: project-dist-release
          path: ./dist

      - name: Vercel deploy
        uses: amondnet/vercel-action@v25
        with:
          working-directory: ./dist
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
