name: Project Dev Build

on:  
  push:    
    branches:
      - main
    paths:
      - 'apps/**'  
  workflow_dispatch:

jobs:
  build-project:
    uses: ./.github/workflows/build-project.yml
    with:
      mode: "dev"

  deploy:
    needs: build-project
    runs-on: ubuntu-slim
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: project-dist-dev
          path: ./dist

      - name: Cloudflare deploy
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: "dist"
          command: pages deploy ./ --project-name=${{ vars.CLOUDFLARE_PROJECT_NAME }} --branch=${{ vars.CLOUDFLARE_PREVIEW_BRANCH }}
